name: Test GitHub Action

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sentiment QA step by 21f1000539@ds.study.iitm.ac.in
        run: |
          echo "Running sentiment analysis test harness"

